In [15]:
import numpy as np


In [16]:
A = np.array([[0, 1, 0, 1, 1],
         [1, 0, 0, 1, 0],
         [0, 0, 0, 0, 1],
         [1, 1, 0, 0, 0],
         [1, 0, 1, 0, 0]])

K = np.array([[1,0,0], 
                     [0,1,0],
                     [1,0,0], 
                     [0,0,1], 
                     [0,1,0]])

In [17]:
import numpy as np

def encode(A, K):
    n, k = K.shape
    M = np.zeros_like(A, dtype=int)
    
    # Compute max indices per row in K
    max_indices = np.argmax(K, axis=1)
    
    # Check how many ones exist in each row
    row_sums = np.sum(K, axis=1)
    
    for i in range(n):
        for j in range(i, n):  # Symmetric encoding
            if A[i, j] == 1:
                M[i, j] = 1  # Base encoding from A
                
                if max_indices[i] == max_indices[j]:  # Matching max index
                    M[i, j] += 2
                
                if row_sums[i] > 1 and row_sums[j] > 1:  # Multiple ones in row
                    M[i, j] += 4
            
            M[j, i] = M[i, j]  # Ensure symmetry
    
    return M

def decode(A, M, k):
    n = A.shape[0]
    K = np.zeros((n, k), dtype=int)
    
    # Recover max indices and rows with multiple ones
    for i in range(n):
        for j in range(n):
            if A[i, j] == 1:
                if M[i, j] >= 3:  # Encodes max index agreement
                    max_index = np.argmax(np.bincount(K[i, :], minlength=k))
                    K[i, max_index] = 1
                
                if M[i, j] >= 5:  # Encodes multiple ones
                    K[i, :] = 1  # Approximation (could refine further)
    
    return K


In [18]:
encoded_A = encode(A, K)
decoded_K = decode(A, encoded_A, 3)

print("Encoded A:\n", encoded_A)
print("Decoded K:\n", decoded_K)

Encoded A:
 [[0 1 0 1 1]
 [1 0 0 1 0]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [1 0 1 0 0]]
Decoded K:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
